{{- if not .Values.apiKeys.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-ai-support.fullname" . }}-secrets
  labels:
    {{- include "k8s-ai-support.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.apiKeys.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.apiKeys.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.apiKeys.geminiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.apiKeys.anthropicApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
